### PR TITLE
Automatically run a bundle analyzer when building Llaminator

### PR DESCRIPTION
**Pull request by beverloo**
Example output: https://llaminator.peter.sh/index-sizes.html

This makes it much easier to understand the impact of code (& especially dependency) changes on our JavaScript bundle size.

### CODE REVIEW

**Comment by PEConn** [comment]
I had a look at the output - I'm not quite sure how I should be using it. It doesn't seem to give a breakdown of where the size comes from - it just says "index + 45 modules" and "index + 70 modules".

If I add a build dependency that's massive, how will I know? Do I need to have kept track of the previous bundle sizes?

**Comment by beverloo** [comment]
You can select "Show content of concatenated modules (inaccurate)" in the drop-over menu, which reveals the actual modules. The sizes displayed for them are the on-disk stat sizes, but the hierarchy works.

**Comment by PEConn** [comment]
Oh cool, that's handy.

Would it be worth adding an `npm run analyze` command?

**Comment by beverloo** [comment]
Running the `build` command ten times with this plugin, and ten times without, the real-time impact is ~62ms on my machine, which is about a percentage of our full build time. Doing this analysis as part of a common developer journey seems more sensible given those numbers than creating a new one, which is easy to forget about.

**Comment by PEConn** [comment]
Cool, and just to check, a link to the report is output as part of the build so that it's easy enough to open it?

**Comment by beverloo** [comment]
The `index-sizes.html` file will be generated and stored in the `dist/` directory, indeed.

**Comment by PEConn** [comment]
Right, but is there output that says that? I can for-see myself wanting to use this feature and not remembering where that file lives.

**Comment by beverloo** [comment]
```
C:\Users\peter\Desktop\GitHub\llaminator>npm run-script build

> llaminator@0.0.1 build
> webpack --mode=production

Webpack Bundle Analyzer saved report to C:\Users\peter\Desktop\GitHub\llaminator\dist\index-sizes.html
assets by status 23.3 KiB [compared for emit]
  asset sw.js 21.6 KiB [emitted] [compared for emit] [minimized]
  asset index.html 890 bytes [emitted] [compared for emit]
  asset manifest.json 885 bytes [compared for emit] [from: public/manifest.json] [copied]
asset llaminator.c5e6f5004ad5ec4e6740.js 80.7 KiB [emitted] [immutable] [minimized] (name: llaminator) 1 related asset
asset llaminator.css 7.36 KiB [emitted] [from: src/llaminator.scss] [minimized] (auxiliary name: llaminator)
orphan modules 163 KiB [orphan] 58 modules
runtime modules 1.06 KiB 2 modules
./src/index.ts + 45 modules 149 KiB [built] [code generated]

LOG from InjectManifest
<i> The service worker at sw.js will precache
<i>         5 URLs, totaling 94.4 kB.

webpack 5.65.0 compiled successfully in 6652 ms
```

So yeah, the very first line above the assets:

```
Webpack Bundle Analyzer saved report to C:\Users\peter\Desktop\GitHub\llaminator\dist\index-sizes.html
```

It has a slightly different colour too, but that doesn't copy well to GitHub comments.

**Review by glennhartmann — APPROVED** [review]

**Pull request merged**
