### PR TITLE
Replace 'process.env.NODE_ENV' in build

### PR DESCRIPTION
**Pull request by glennhartmann**
Fixes:

Uncaught ReferenceError: process is not defined at
node_modules/workbox-core/models/messages/messageGenerator.js:24

### CODE REVIEW

**Comment by andreban** [comment]
Interesting - is this error happening in a browser environment? Looking at the WorkBox code, it seems to expect this to always in Node environment (https://github.com/GoogleChrome/workbox/blob/8afb37210d8f4fe62847f4e80e42fc95bced4895/packages/workbox-core/src/models/messages/messageGenerator.ts#L29-L30). @jeffposnick @tropicadri is this indeed the case?

**Comment by jeffposnick** [comment]
The use case is described at https://developers.google.com/web/tools/workbox/guides/using-bundlers#configure_your_bundler_for_a_development_or_production_build

If you're creating your own bundles then the expectation is that you'll toggle between development and production mode based on the `NODE_ENV` environment variable. (If you'd prefer to use a pre-made bundle, we also publish those to NPM under the `/build/` subdirectory directory, i.e. `'workbox-routing/build/workbox-routing.dev.js'` or `'workbox-routing/build/workbox-routing.prod.js'`.)

We are steering most folks towards creating their own bundles nowadays, though.

**Comment by glennhartmann** [comment]
> Interesting - is this error happening in a browser environment?

Not sure, the browser environment currently has other bugs... https://github.com/GoogleChromeLabs/llaminator/issues/19

**Comment by glennhartmann** [comment]
> > Interesting - is this error happening in a browser environment?
> 
> Not sure, the browser environment currently has other bugs... #19

with https://github.com/GoogleChromeLabs/llaminator/pull/32 I can confirm that this happens in the browser environment

**Comment by jeffposnick** [comment]
We have a guide at https://developers.google.com/web/tools/workbox/guides/using-bundlers explaining how to produce a bundled file that should be runnable as the service worker in a browser, and does not require being registered via `{type: 'module'}` (which has compatibility issues, especially in Firefox).

If you'd prefer not to generate a bundle for some reason, there's a "CDN" copy of the Workbox runtime libraries that's loadable via `importScripts()`. That's documented at https://developers.google.com/web/tools/workbox/modules/workbox-sw

**Comment by glennhartmann** [comment]
> We have a guide at https://developers.google.com/web/tools/workbox/guides/using-bundlers explaining how to produce a bundled file that should be runnable as the service worker in a browser, and does not require being registered via `{type: 'module'}` (which has compatibility issues, especially in Firefox).
> 
> If you'd prefer not to generate a bundle for some reason, there's a "CDN" copy of the Workbox runtime libraries that's loadable via `importScripts()`. That's documented at https://developers.google.com/web/tools/workbox/modules/workbox-sw

Yeah, we used to use the CDN (https://github.com/GoogleChromeLabs/llaminator/blob/f0597dff3a382e608d261853424dbdee69a21a7f/sw.js) but I hoped to be able to share code and import `node` stuff more easily.

We can do bundling for `releases`, but it doesn't look like there's a way to make that play nice with our dev server's `--watch` mode (https://modern-web.dev/docs/dev-server/plugins/rollup/#bundling)

**Comment by glennhartmann** [comment]
I believe this is obsolete due to https://github.com/GoogleChromeLabs/llaminator/pull/35

**Pull request closed without merging**
